%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosPropertyService_PropertySet
%% Source: /builddir/build/BUILD/otp_src_R14B04/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSPROPERTYSERVICE_PROPERTYSET_HRL).
-define(COSPROPERTYSERVICE_PROPERTYSET_HRL, true).




-endif.


