%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_StructuredPullSupplier
%% Source: /builddir/build/BUILD/otp_src_R14B04/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_STRUCTUREDPULLSUPPLIER_HRL).
-define(COSNOTIFYCOMM_STRUCTUREDPULLSUPPLIER_HRL, true).




-endif.


