%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotificationComm
%% Source: /builddir/build/BUILD/otp_src_R14B04/lib/cosNotification/src/cosNotificationAppComm.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFICATIONCOMM_HRL).
-define(OE_COSNOTIFICATIONCOMM_HRL, true).




-endif.


