.TH CosTransactions_TransactionFactory 3 "cosTransactions 1.2.11" "Ericsson AB" "Erlang Module Definition"
.SH NAME
CosTransactions_TransactionFactory \- This module implements the OMG CosTransactions::TransactionFactory interface.
.SH DESCRIPTION
.LP
To get access to the record definitions for the structures use: 
.br
\fI-include_lib("cosTransactions/include/CosTransactions\&.hrl")\&.\fR\&
.SH EXPORTS
.LP
.B
create(TransactionFactory, Timeout) -> Control
.br
.RS
.TP 3
Types:

TransactionFactory = #objref
.br
Timeout = integer()
.br
Control = #objref
.br
.RE
.RS
.LP
This operation creates a new top-level transaction\&.
.LP
The \fITimeout\fR\& argument can be:
.RS 2
.TP 2
*
0 - no timeout\&.
.LP
.TP 2
*
N (integer() > 0) - the transaction will be subject to being rolled back if it does not complete before N seconds have elapsed\&.
.LP
.RE

.RE