.TH diameter_tcp 3 "diameter 0.10" "Ericsson AB" "Erlang Module Definition"
.SH NAME
diameter_tcp \- Diameter transport over TCP.
.SH DESCRIPTION
.LP
This module implements diameter transport over TCP using gen_tcp\&. It can be specified as the value of a transport_module option to \fBdiameter:add_transport/2\fR\& and implements the behaviour documented in \fBdiameter_transport(3)\fR\&\&.
.SH EXPORTS
.LP
.B
start({Type, Ref}, Svc, [Opt]) -> {ok, Pid, [LAddr]} | {error, Reason}
.br
.RS
.TP 3
Types:

Type = connect | accept
.br
Ref = reference()
.br
Svc = #diameter_service{}
.br
Opt = {raddr, ip_address()} | {rport, integer()} | term()
.br
Pid = pid()
.br
LAddr = ip_address()
.br
Reason = term()
.br
.RE
.RS
.LP
The start function required by \fBdiameter_transport(3)\fR\&\&.
.LP
The only diameter_tcp-specific argument is the options list\&. Options \fIraddr\fR\& and \fIrport\fR\& specify the remote address and port for a connecting transport and not valid for a listening transport\&. Remaining options are any accepted by gen_tcp:connect/3 for a connecting transport, or gen_tcp:listen/2 for a listening transport, with the exception of \fIbinary\fR\&, \fIpacket\fR\& and \fIactive\fR\&\&. Also, option \fIport\fR\& can be specified for a listening transport to specify the local listening port, the default being the standardized 3868 if unspecified\&. Note that option \fIip\fR\& specifies the local address\&.
.LP
If the service specifies more than one Host-IP-Address and option \fIip\fR\& is unspecified then then the first of the service\&'s addresses is used as the local address\&.
.LP
The returned local address list has length one\&.
.RE
.SH "SEE ALSO"

.LP
\fBdiameter_transport(3)\fR\&