.TH edoc_lib 3 "edoc 0.7.9" "" "Erlang Module Definition"
.SH NAME
edoc_lib \- Utility functions for EDoc.
.SH DESCRIPTION
.LP
Utility functions for EDoc\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIedoc_env()\fR\&:

.RS 2
.LP
Environment information needed by EDoc for generating references\&. The data representation is not documented\&.
.RE
.TP 2
.B
\fIproplist() = property() (see module proplists)\fR\&:

.RE
.SH EXPORTS
.LP
.B
get_doc_env(App, Packages, Modules, Options::proplist()) -> edoc_env()
.br
.RS
.TP 3
Types:

App = [] | atom()
.br
Packages = [atom()]
.br
Modules = [atom()]
.br
[term()]
.br
.RE
.RS
.LP
Creates an environment data structure used by parts of EDoc for generating references, etc\&. See \fBedoc:run/3\fR\& for a description of the options \fIfile_suffix\fR\&, \fIapp_default\fR\& and \fIdoc_path\fR\&\&.
.LP
\fISee also:\fR\& \fBedoc:get_doc/3\fR\&, \fBedoc_extract:source/4\fR\&\&.
.RE
.SH "SEE ALSO"

.LP
\fBedoc\fR\&
.SH AUTHORS
.LP
Richard Carlsson
.I
<carlsson\&.richard@gmail\&.com>