.TH erl_prim_loader 3 "kernel 2.14.5" "Ericsson AB" "Erlang Module Definition"
.SH NAME
erl_prim_loader \- Low Level Erlang Loader
.SH DESCRIPTION
.LP
The module erl_prim_loader is moved to the runtime system application\&. Please see \fBerl_prim_loader(3)\fR\& in the erts reference manual instead\&.