.TH et 3 "et 1.4.4" "Ericsson AB" "Erlang Module Definition"
.SH NAME
et \- Main API of the Event Trace (ET) application
.SH DESCRIPTION
.LP
Interface module for the Event Trace (ET) application
.SH EXPORTS
.LP
.B
trace_me(DetailLevel, From, To, Label, Contents) -> hopefully_traced
.br
.RS
.TP 3
Types:

DetailLevel = integer(X) when X =< 0, X >= 100
.br
From = actor()
.br
To = actor()
.br
Label = atom() | string() | term()
.br
Contents = [{Key, Value}] | term()
.br
actor() = term()
.br
.RE
.RS
.LP
A function that is intended to be traced\&.
.LP
This function is intended to be invoked at strategic places in user applications in order to enable simplified tracing\&. The functions are extremely light weight as they do nothing besides returning an atom\&. The functions are designed for being traced\&. The global tracing mechanism in \fIet_collector\fR\& defaults to set its trace pattern to these functions\&.
.LP
The label is intended to provide a brief summary of the event\&. It is preferred to use an atom but a string would also do\&.
.LP
The contents can be any term but in order to simplify post processing of the traced events, a plain list of {Key, Value} tuples is preferred\&.
.LP
Some events, such as messages, are directed from some actor to another\&. Other events (termed actions) may be undirected and only have one actor\&.
.RE
.LP
.B
trace_me(DetailLevel, FromTo, Label, Contents) -> hopefully_traced
.br
.RS
.LP
Invokes \fIet:trace_me/5\fR\& with both \fIFrom\fR\& and \fITo\fR\& set to \fIFromTo\fR\&\&.
.RE
.LP
.B
phone_home(DetailLevel, FromTo, Label, Contents) -> hopefully_traced
.br
.B
phone_home(DetailLevel, From, To, Label, Contents) -> hopefully_traced
.br
.RS
.LP
These functions sends a signal to the outer space and the caller hopes that someone is listening\&. In other words, they invoke \fIet:trace_me/4\fR\& and \fIet:trace_me/5\fR\& respectively\&.
.RE
.LP
.B
report_event(DetailLevel, FromTo, Label, Contents) -> hopefully_traced
.br
.B
report_event(DetailLevel, From, To, Label, Contents) -> hopefully_traced
.br
.RS
.LP
Deprecated functions which for the time being are kept for backwards compatibility\&. Invokes \fIet:trace_me/4\fR\& and \fIet:trace_me/5\fR\& respectively\&.
.RE