.TH lname_component 3 "orber 3.6.22" "Ericsson AB" "Erlang Module Definition"
.SH NAME
lname_component \- Interface that supports the name pseudo-objects.
.SH DESCRIPTION
.LP
This interface is a part of the name library, which is used to hide the representation of names\&. In Orbers Erlang mapping the pseudo-object names and the real IDL names have the same representation but it is desirable that the clients uses the names library so they will not be dependent of the representation\&. The lname_component interface supports handling of name components e\&.g\&. set and get of the struct members\&.
.LP
Note that the lname_component interface in orber does not contain a destroy function because the NameComponents are represented as Erlang records and therefor will be removed by the garbage collector when not in use\&.
.LP
The type \fINameComponent\fR\& used below is defined as:
.LP
.nf

      -record('CosNaming_NameComponent', {id, kind=""}).
    
.fi
.LP
\fIid\fR\& and \fIkind\fR\& are strings\&.
.LP
The record is defined in the file \fICosNaming\&.hrl\fR\& and it is included with:
.LP
.nf

      -include_lib("orber/COSS/CosNaming/CosNaming.hrl").
    
.fi
.SH EXPORTS
.LP
.B
create() -> Return
.br
.RS
.TP 3
Types:

Return = NameComponent
.br
.RE
.RS
.LP
This function returns a new name component\&.
.RE
.LP
.B
get_id(NameComponent) -> Return
.br
.RS
.TP 3
Types:

Return = string()
.br
.RE
.RS
.LP
This function returns the id string of a name component\&.
.RE
.LP
.B
set_id(NameComponent, Id) -> Return
.br
.RS
.TP 3
Types:

Id = string()
.br
Return = NameComponent
.br
.RE
.RS
.LP
This function sets the id string of a name component and returns the component\&.
.RE
.LP
.B
get_kind(NameComponent) -> Return
.br
.RS
.TP 3
Types:

Return = string()
.br
.RE
.RS
.LP
This function returns the id string of a name component\&.
.RE
.LP
.B
set_kind(NameComponent, Kind) -> Return
.br
.RS
.TP 3
Types:

Kind = string()
.br
Return = NameComponent
.br
.RE
.RS
.LP
This function sets the kind string of a name component and returns the component\&.
.RE