.TH megaco_user 3 "megaco 3.15.1.1" "Ericsson AB" "Erlang Module Definition"
.SH NAME
megaco_user \- Callback module for users of the Megaco application
.SH DESCRIPTION
.LP
This module defines the callback behaviour of Megaco users\&. A megaco_user compliant callback module must export the following functions:
.RS 2
.TP 2
*
\fBhandle_connect/2,3\fR\&
.LP
.TP 2
*
\fBhandle_disconnect/3\fR\&
.LP
.TP 2
*
\fBhandle_syntax_error/3,4\fR\&
.LP
.TP 2
*
\fBhandle_message_error/3,4\fR\&
.LP
.TP 2
*
\fBhandle_trans_request/3,4\fR\&
.LP
.TP 2
*
\fBhandle_trans_long_request/3,4\fR\&
.LP
.TP 2
*
\fBhandle_trans_reply/4,5\fR\&
.LP
.TP 2
*
\fBhandle_trans_ack/4,5\fR\&
.LP
.TP 2
*
\fBhandle_unexpected_trans/3,4\fR\&
.LP
.TP 2
*
\fBhandle_trans_request_abort/4,5\fR\&
.LP
.TP 2
*
\fBhandle_segment_reply/5,6\fR\&
.LP
.RE

.LP
The semantics of them and their exact signatures are explained below\&.
.LP
The \fIuser_args\fR\& configuration parameter which may be used to extend the argument list of the callback functions\&. For example, the handle_connect function takes by default two arguments:
.LP
.nf

        handle_connect(Handle, Version)
    
.fi
.LP
but if the \fIuser_args\fR\& parameter is set to a longer list, such as \fI[SomePid,SomeTableRef]\fR\&, the callback function is expected to have these (in this case two) extra arguments last in the argument list:
.LP
.nf

        handle_connect(Handle, Version, SomePid, SomeTableRef)
    
.fi
.LP

.RS -4
.B
Note:
.RE
Must of the functions below has an optional \fIExtra\fR\& argument (e\&.g\&. \fBhandle_unexpected_trans/4\fR\&)\&. The functions which takes this argument will be called if and only if one of the functions \fBreceive_message/5\fR\& or \fBprocess_received_message/5\fR\& was called with the \fIExtra\fR\& argument different than \fIignore_extra\fR\&\&.

.SH "DATA TYPES"

.LP
.nf

action_request() = #'ActionRequest'{}
action_reply() = #'ActionReply'{}
error_desc() = #'ErrorDescriptor'{}
segment_no() = integer()
    
.fi
.LP
.nf

conn_handle() = #megaco_conn_handle{}    
.fi
.LP
The record initially returned by \fImegaco:connect/4,5\fR\&\&. It identifies a "virtual" connection and may be reused after a reconnect (disconnect + connect)\&.
.LP
.nf

protocol_version() = integer()    
.fi
.LP
Is the actual protocol version\&. In most cases the protocol version is retrieved from the processed message, but there are exceptions:
.LP

.RS 2
.TP 2
*
When \fIhandle_connect/2,3\fR\& is triggered by an explicit call to \fImegaco:connect/4,5\fR\&\&.
.LP
.TP 2
*
\fIhandle_disconnect/3\fR\&
.LP
.TP 2
*
\fIhandle_syntax_error/3\fR\&
.LP
.RE

.LP
In these cases, the ProtocolVersion default version is obtained from the static connection configuration:
.RS 2
.TP 2
*
\fImegaco:conn_info(ConnHandle, protocol_version)\fR\&\&.
.LP
.RE

.SH EXPORTS
.LP
.B
handle_connect(ConnHandle, ProtocolVersion) -> ok | error | {error,ErrorDescr}
.br
.B
handle_connect(ConnHandle, ProtocolVersion, Extra]) -> ok | error | {error,ErrorDescr}
.br
.RS
.TP 3
Types:

ConnHandle = conn_handle()
.br
ProtocolVersion = protocol_version()
.br
ErrorDescr = error_desc()
.br
Extra = term()
.br
.RE
.RS
.LP
Invoked when a new connection is established
.LP
Connections may either be established by an explicit call to megaco:connect/4 or implicitly at the first invocation of megaco:receive_message/3\&.
.LP
Normally a Media Gateway (MG) connects explicitly while a Media Gateway Controller (MGC) connects implicitly\&.
.LP
At the Media Gateway Controller (MGC) side it is possible to reject a connection request (and send a message error reply to the gateway) by returning \fI{error, ErrorDescr}\fR\& or simply \fIerror\fR\& which generates an error descriptor with code 402 (unauthorized) and reason "Connection refused by user" (this is also the case for all unknown results, such as exit signals or throw)\&.
.LP
See \fBnote\fR\& above about the \fIExtra\fR\& argument in \fIhandle_message_error/4\fR\&\&.
.LP
\fIhandle_connect/3\fR\& (with \fIExtra\fR\&) can also be called as a result of a call to the \fBmegaco:connect/5\fR\& function (if that function is called with the \fIExtra\fR\& argument different than \fIignore_extra\fR\&\&.
.RE
.LP
.B
handle_disconnect(ConnHandle, ProtocolVersion, Reason) -> ok
.br
.RS
.TP 3
Types:

ConnHandle = conn_handle()
.br
ProtocolVersion = protocol_version()
.br
Reason = term()
.br
.RE
.RS
.LP
Invoked when a connection is teared down
.LP
The disconnect may either be made explicitly by a call to megaco:disconnect/2 or implicitly when the control process of the connection dies\&.
.RE
.LP
.B
handle_syntax_error(ReceiveHandle, ProtocolVersion, DefaultED) -> reply | {reply, ED} | no_reply | {no_reply, ED} 
.br
.B
handle_syntax_error(ReceiveHandle, ProtocolVersion, DefaultED, Extra) -> reply | {reply, ED} | no_reply | {no_reply, ED} 
.br
.RS
.TP 3
Types:

ReceiveHandle = receive_handle()
.br
ProtocolVersion = protocol_version()
.br
DefaultED = error_desc()
.br
ED = error_desc()
.br
Extra = term()
.br
.RE
.RS
.LP
Invoked when a received message had syntax errors
.LP
Incoming messages is delivered by megaco:receive_message/4 and normally decoded successfully\&. But if the decoding failed this function is called in order to decide if the originator should get a reply message (reply) or if the reply silently should be discarded (no_reply)\&.
.LP
Syntax errors are detected locally on this side of the protocol and may have many causes, e\&.g\&. a malfunctioning transport layer, wrong encoder/decoder selected, bad configuration of the selected encoder/decoder etc\&.
.LP
The error descriptor defaults to \fIDefaultED\fR\&, but can be overridden with an alternate one by returning \fI{reply,ED}\fR\& or \fI{no_reply,ED}\fR\& instead of \fIreply\fR\& and \fIno_reply\fR\& respectively\&.
.LP
Any other return values (including exit signals or throw) and the \fIDefaultED\fR\& will be used\&.
.LP
See \fBnote\fR\& above about the \fIExtra\fR\& argument in \fIhandle_syntax_error/4\fR\&\&.
.RE
.LP
.B
handle_message_error(ConnHandle, ProtocolVersion, ErrorDescr) -> ok
.br
.B
handle_message_error(ConnHandle, ProtocolVersion, ErrorDescr, Extra) -> ok
.br
.RS
.TP 3
Types:

ConnHandle = conn_handle()
.br
ProtocolVersion = protocol_version()
.br
ErrorDescr = error_desc()
.br
Extra = term()
.br
.RE
.RS
.LP
Invoked when a received message just contains an error instead of a list of transactions\&.
.LP
Incoming messages is delivered by megaco:receive_message/4 and successfully decoded\&. Normally a message contains a list of transactions, but it may instead contain an ErrorDescriptor on top level of the message\&.
.LP
Message errors are detected remotely on the other side of the protocol\&. And you probably don\&'t want to reply to it, but it may indicate that you have outstanding transactions that not will get any response (request -> reply; reply -> ack)\&.
.LP
See \fBnote\fR\& above about the \fIExtra\fR\& argument in \fIhandle_message_error/4\fR\&\&.
.RE
.LP
.B
handle_trans_request(ConnHandle, ProtocolVersion, ActionRequests) -> pending() | reply() | ignore_trans_request
.br
.B
handle_trans_request(ConnHandle, ProtocolVersion, ActionRequests, Extra) -> pending() | reply() | ignore_trans_request
.br
.RS
.TP 3
Types:

ConnHandle = conn_handle()
.br
ProtocolVersion = protocol_version()
.br
ActionRequests = [action_request()]
.br
Extra = term()
.br
pending() = {pending, req_data()}
.br
req_data() = term()
.br
reply() = {ack_action(), actual_reply()} | {ack_action(), actual_reply(), send_options()}
.br
ack_action() = discard_ack | {handle_ack, ack_data()} | {handle_pending_ack, ack_data()} | {handle_sloppy_ack, ack_data()}
.br
actual_reply() = [action_reply()] | error_desc()
.br
ack_data() = term()
.br
send_options() = [send_option()]
.br
send_option() = {reply_timer, megaco_timer()} | {send_handle, term()} | {protocol_version, integer()}
.br
Extra = term()
.br
.RE
.RS
.LP
Invoked for each transaction request
.LP
Incoming messages is delivered by megaco:receive_message/4 and successfully decoded\&. Normally a message contains a list of transactions and this function is invoked for each TransactionRequest in the message\&.
.LP
This function takes a list of \&'ActionRequest\&' records and has three main options:
.RS 2
.TP 2
.B
\fIReturn ignore_trans_request\fR\&:
Decide that these action requests shall be ignored completely\&.
.TP 2
.B
\fIReturn pending()\fR\&:
Decide that the processing of these action requests will take a long time and that the originator should get an immediate \&'TransactionPending\&' reply as interim response\&. The actual processing of these action requests instead should be delegated to the the handle_trans_long_request/3 callback function with the req_data() as one of its arguments\&.
.TP 2
.B
\fIReturn reply()\fR\&:
Process the action requests and either return an error_descr() indicating some fatal error or a list of action replies (wildcarded or not)\&.
.RS 2
.LP
If for some reason megaco is unable to deliver the reply, the reason for this will be passed to the user via a call to the callback function \fBhandle_trans_ack\fR\&, unless \fIack_action() = discard_ack\fR\&\&.
.RE
.RS 2
.LP
The ack_action() is either:
.RE
.RS 2
.TP 2
.B
\fIdiscard_ack\fR\&:
Meaning that you don\&'t care if the reply is acknowledged or not\&.
.TP 2
.B
\fI{handle_ack, ack_data()} | {handle_ack, ack_data(), send_options()}\fR\&:
Meaning that you want an immediate acknowledgement when the other part receives this transaction reply\&. When the acknowledgement eventually is received, the handle_trans_ack/4 callback function will be invoked with the ack_data() as one of its arguments\&. ack_data() may be any Erlang term\&.
.TP 2
.B
\fI{handle_pending_ack, ack_data()} | {handle_pending_ack, ack_data(), send_options()}\fR\&:
This has the same effect as the above, \fIif and only if\fR\& megaco has sent at least one pending message for this request (during the processing of the request)\&. If no pending message has been sent, then immediate acknowledgement will \fInot\fR\& be requested\&.
.RS 2
.LP
Note that this only works as specified if the \fIsent_pending_limit\fR\& config option has been set to an integer value\&.
.RE
.TP 2
.B
\fI{handle_sloppy_ack, ack_data()}| {handle_sloppy_ack, ack_data(), send_options()}\fR\&:
Meaning that you want an acknowledgement \fIsometime\fR\&\&. When the acknowledgement eventually is received, the handle_trans_ack/4 callback function will be invoked with the ack_data() as one of its arguments\&. ack_data() may be any Erlang term\&.
.RE
.RE
.LP
Any other return values (including exit signals or throw) will result in an error descriptor with code 500 (internal gateway error) and the module name (of the callback module) as reason\&.
.LP
See \fBnote\fR\& above about the \fIExtra\fR\& argument in \fIhandle_trans_request/4\fR\&\&.
.RE
.LP
.B
handle_trans_long_request(ConnHandle, ProtocolVersion, ReqData) -> reply()
.br
.B
handle_trans_long_request(ConnHandle, ProtocolVersion, ReqData, Extra) -> reply()
.br
.RS
.TP 3
Types:

ConnHandle = conn_handle()
.br
ProtocolVersion = protocol_version()
.br
ReqData = req_data()
.br
Extra = term()
.br
req_data() = term()
.br
reply() = {ack_action(), actual_reply()} | {ack_action(), actual_reply(), send_options()}
.br
ack_action() = discard_ack | {handle_ack, ack_data()} | {handle_sloppy_ack, ack_data()}
.br
actual_reply() = [action_reply()] | error_desc()
.br
ack_data() = term()
.br
send_options() = [send_option()]
.br
send_option() = {reply_timer, megaco_timer()} | {send_handle, term()} | {protocol_version, integer()}
.br
Extra = term()
.br
.RE
.RS
.LP
Optionally invoked for a time consuming transaction request
.LP
If this function gets invoked or not is controlled by the reply from the preceding call to handle_trans_request/3\&. The handle_trans_request/3 function may decide to process the action requests itself or to delegate the processing to this function\&.
.LP
The req_data() argument to this function is the Erlang term returned by handle_trans_request/3\&.
.LP

.LP
Any other return values (including exit signals or throw) will result in an error descriptor with code 500 (internal gateway error) and the module name (of the callback module) as reason\&.
.LP
See \fBnote\fR\& above about the \fIExtra\fR\& argument in \fIhandle_trans_long_request/4\fR\&\&.
.RE
.LP
.B
handle_trans_reply(ConnHandle, ProtocolVersion, UserReply, ReplyData) -> ok
.br
.B
handle_trans_reply(ConnHandle, ProtocolVersion, UserReply, ReplyData, Extra) -> ok
.br
.RS
.TP 3
Types:

ConnHandle = conn_handle()
.br
ProtocolVersion = protocol_version()
.br
UserReply = success() | failure()
.br
success() = {ok, result()}
.br
result() = transaction_result() | segment_result()
.br
transaction_result() = action_reps()
.br
segment_result() = {segment_no(), last_segment(), action_reps()}
.br
action_reps() = [action_reply()]
.br
failure() = {error, reason()} | {error, ReplyNo, reason()}
.br
reason() = transaction_reason() | segment_reason() | user_cancel_reason() | send_reason() | other_reason()
.br
transaction_reason() = error_desc()
.br
segment_reason() = {segment_no(), last_segment(), error_desc()}
.br
other_reason() = timeout | {segment_timeout, missing_segments()} | exceeded_recv_pending_limit | term()
.br
last_segment() = bool()
.br
missing_segments() = [segment_no()]
.br
user_cancel_reason() = {user_cancel, reason_for_user_cancel()}
.br
reason_for_user_cancel() = term()
.br
send_reason() = send_cancelled_reason() | send_failed_reason()
.br
send_cancelled_reason() = {send_message_cancelled, reason_for_send_cancel()}
.br
reason_for_send_cancel() = term()
.br
send_failed_reason() = {send_message_failed, reason_for_send_failure()}
.br
reason_for_send_failure() = term()
.br
ReplyData = reply_data()
.br
ReplyNo = integer() > 0
.br
reply_data() = term()
.br
Extra = term()
.br
.RE
.RS
.LP
Optionally invoked for a transaction reply
.LP
The sender of a transaction request has the option of deciding, whether the originating Erlang process should synchronously wait (\fImegaco:call/3\fR\&) for a reply or if the message should be sent asynchronously (\fImegaco:cast/3\fR\&) and the processing of the reply should be delegated this callback function\&.
.LP
Note that if the reply is segmented (split into several smaller messages; segments), then some extra info, segment number and an indication if all segments of a reply has been received or not, is also included in the \fIUserReply\fR\&\&.
.LP
The \fIReplyData\fR\& defaults to \fImegaco:lookup(ConnHandle, reply_data)\fR\&, but may be explicitly overridden by a \fImegaco:cast/3\fR\& option in order to forward info about the calling context of the originating process\&.
.LP
At \fIsuccess()\fR\&, the \fIUserReply\fR\& either contains:
.RS 2
.TP 2
*
A list of \&'ActionReply\&' records possibly containing error indications\&.
.LP
.TP 2
*
A tuple of size three containing: the segment number, the \fIlast segment indicator\fR\& and finally a list of \&'ActionReply\&' records possibly containing error indications\&. This is of course only possible if the reply was segmented\&.
.LP
.RE

.LP
\fIfailure()\fR\& indicates an local or external error and can be one of the following:
.RS 2
.TP 2
*
A \fItransaction_reason()\fR\&, indicates that the remote user has replied with an explicit transactionError\&.
.LP
.TP 2
*
A \fIsegment_reason()\fR\&, indicates that the remote user has replied with an explicit transactionError for this segment\&. This is of course only possible if the reply was segmented\&.
.LP
.TP 2
*
A \fIuser_cancel_reason()\fR\&, indicates that the request has been canceled by the user\&. \fIreason_for_user_cancel()\fR\& is the reason given in the call to the \fBcancel\fR\& function\&.
.LP
.TP 2
*
A \fIsend_reason()\fR\&, indicates that the transport module \fBsend_message\fR\& function did not send the message\&. The reason for this can be:
.RS 2
.TP 2
*
\fIsend_cancelled_reason()\fR\& - the message sending was deliberately cancelled\&. \fIreason_for_send_cancel()\fR\& is the reason given in the \fIcancel\fR\& return from the \fBsend_message\fR\& function\&.
.LP
.TP 2
*
\fIsend_failed_reason()\fR\& - an error occurred while attempting to send the message\&.
.LP
.RE

.LP
.TP 2
*
An \fIother_reason()\fR\&, indicates some other error such as:
.RS 2
.TP 2
*
\fItimeout\fR\& - the reply failed to arrive before the request timer expired\&.
.LP
.TP 2
*
\fI{segment_timeout, missing_segments()}\fR\& - one or more segments was not delivered before the expire of the segment timer\&.
.LP
.TP 2
*
\fIexceeded_recv_pending_limit\fR\& - the pending limit was exceeded for this request\&.
.LP
.RE

.LP
.RE

.LP
See \fBnote\fR\& above about the \fIExtra\fR\& argument in \fIhandle_trans_reply/5\fR\&\&.
.RE
.LP
.B
handle_trans_ack(ConnHandle, ProtocolVersion, AckStatus, AckData) -> ok
.br
.B
handle_trans_ack(ConnHandle, ProtocolVersion, AckStatus, AckData, Extra) -> ok
.br
.RS
.TP 3
Types:

ConnHandle = conn_handle()
.br
ProtocolVersion = protocol_version()
.br
AckStatus = ok | {error, reason()}
.br
reason() = user_cancel_reason() | send_reason() | other_reason()
.br
user_cancel_reason() = {user_cancel, reason_for_user_cancel()}
.br
send_reason() = send_cancelled_reason() | send_failed_reason()
.br
send_cancelled_reason() = {send_message_cancelled, reason_for_send_cancel()}
.br
reason_for_send_cancel() = term()
.br
send_failed_reason() = {send_message_failed, reason_for_send_failure()}
.br
reason_for_send_failure() = term()
.br
other_reason() = term()
.br
AckData = ack_data()
.br
ack_data() = term()
.br
Extra = term()
.br
.RE
.RS
.LP
Optionally invoked for a transaction acknowledgement
.LP
If this function gets invoked or not, is controlled by the reply from the preceding call to handle_trans_request/3\&. The handle_trans_request/3 function may decide to return {handle_ack, ack_data()} or {handle_sloppy_ack, ack_data()} meaning that you need an immediate acknowledgement of the reply and that this function should be invoked to handle the acknowledgement\&.
.LP
The ack_data() argument to this function is the Erlang term returned by handle_trans_request/3\&.
.LP

.LP
If the AckStatus is ok, it is indicating that this is a true acknowledgement of the transaction reply\&.
.LP
If the AckStatus is {error, Reason}, it is an indication that the acknowledgement or even the reply (for which this is an acknowledgement) was not delivered, but there is no point in waiting any longer for it to arrive\&. This happens when:
.RS 2
.TP 2
.B
\fIreply_timer\fR\&:
The \fIreply_timer\fR\& eventually times out\&.
.TP 2
.B
reply send failure:
When megaco fails to send the reply (see \fBhandle_trans_reply\fR\&), for whatever reason\&.
.TP 2
.B
cancel:
The user has explicitly cancelled the wait (megaco:cancel/2)\&.
.RE
.LP
See \fBnote\fR\& above about the \fIExtra\fR\& argument in \fIhandle_trans_ack/5\fR\&\&.
.RE
.LP
.B
handle_unexpected_trans(ConnHandle, ProtocolVersion, Trans) -> ok
.br
.B
handle_unexpected_trans(ConnHandle, ProtocolVersion, Trans, Extra) -> ok
.br
.RS
.TP 3
Types:

ConnHandle = conn_handle()
.br
ProtocolVersion = protocol_version()
.br
Trans = #'TransactionPending'{} | #'TransactionReply'{} | #'TransactionResponseAck'{}
.br
Extra = term()
.br
.RE
.RS
.LP
Invoked when a unexpected message is received
.LP
If a reply to a request is not received in time, the megaco stack removes all info about the request from its tables\&. If a reply should arrive after this has been done the app has no way of knowing where to send this message\&. The message is delivered to the "user" by calling this function on the local node (the node which has the link)\&.
.LP
See \fBnote\fR\& above about the \fIExtra\fR\& argument in \fIhandle_unexpected_trans/4\fR\&\&.
.RE
.LP
.B
handle_trans_request_abort(ConnHandle, ProtocolVersion, TransNo, Pid) -> ok
.br
.B
handle_trans_request_abort(ConnHandle, ProtocolVersion, TransNo, Pid, Extra) -> ok
.br
.RS
.TP 3
Types:

ConnHandle = conn_handle()
.br
ProtocolVersion = protocol_version()
.br
TransNo = integer()
.br
Pid = undefined | pid()
.br
Extra = term()
.br
.RE
.RS
.LP
Invoked when a transaction request has been aborted
.LP
This function is invoked if the originating pending limit has been exceeded\&. This usually means that a request has taken abnormally long time to complete\&.
.LP
See \fBnote\fR\& above about the \fIExtra\fR\& argument in \fIhandle_trans_request_abort/5\fR\&\&.
.RE
.LP
.B
handle_segment_reply(ConnHandle, ProtocolVersion, TransNo, SegNo, SegCompl) -> ok
.br
.B
handle_segment_reply(ConnHandle, ProtocolVersion, TransNo, SegNo, SegCompl, Extra) -> ok
.br
.RS
.TP 3
Types:

ConnHandle = conn_handle()
.br
ProtocolVersion = protocol_version()
.br
TransNo = integer()
.br
SegNo = integer()
.br
SegCompl = asn1_NOVALUE | 'NULL'
.br
Extra = term()
.br
.RE
.RS
.LP
This function is called when a segment reply has been received if the \fBsegment_reply_ind\fR\& config option has been set to true\&.
.LP
This is in effect a progress report\&.
.LP
See \fBnote\fR\& above about the \fIExtra\fR\& argument in \fIhandle_segment_reply/6\fR\&\&.
.RE