.TH toolbar 3 "toolbar 1.4.2" "Ericsson AB" "Erlang Module Definition"
.SH NAME
toolbar \- GUI for Starting Tools and User Contributions
.SH DESCRIPTION
.LP
Toolbar makes it easier to use the different Erlang tools - and the user contributions - which are provided\&. It has a graphical user interface with an icon for each tool\&. Clicking the icon activates the corresponding tool\&.
.LP
All tools to be included on Toolbar must have a configuration file containing information about the tool, for example its start function and help information location\&. Configuration files must have the \fI\&.tool\fR\& suffix\&.
.LP
When started, Toolbar automatically checks for \fI*\&.tool\fR\& files in the current path and adds the corresponding tools\&. For each \fIebin\fR\& directory found in the path, it will also look in a \fIpriv\fR\& directory next to it\&. This is a feature of the Erlang file structure\&.
.SH EXPORTS
.LP
.B
start() -> ok | already_started
.br
.RS
.LP
Creates a window containing tool icons\&.
.RE
.LP
.B
version() -> string()
.br
.RS
.LP
Returns the current version number of Toolbar\&.
.RE
.LP
.B
update() -> ok | {error,not_started}
.br
.RS
.LP
Makes a search for new tool files in the current path and adds the corresponding tools to Toolbar window\&.
.RE
.LP
.B
quit() -> ok | {error,not_started}
.br
.LP
.B
create_tool_file() -> ok | {error,not_started}
.br
.RS
.LP
Starts the GUI used for creating and editing tool files\&.
.RE
.LP
.B
add_gs_contribs() -> ok | {error,not_started}
.br
.RS
.LP
Adds the path to the directory where the GS contributions are situated and add the tools found there, if any\&.
.RE