.TH wxBitmapButton 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxBitmapButton \- See external documentation: wxBitmapButton.
.SH DESCRIPTION
.LP
See external documentation: wxBitmapButton\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxButton\fR\& 
.br
\fBwxControl\fR\& 
.br
\fBwxWindow\fR\& 
.br
\fBwxEvtHandler\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxBitmapButton()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxBitmapButton()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Parent::wxWindow() (see module wxWindow), Id::integer(), Bitmap::wxBitmap() (see module wxBitmap)) -> wxBitmapButton()
.br
.RS
.LP
Equivalent to \fBnew(Parent, Id, Bitmap, [])\fR\&\&.
.RE
.LP
.B
new(Parent::wxWindow() (see module wxWindow), Id::integer(), Bitmap::wxBitmap() (see module wxBitmap), Options::[Option]) -> wxBitmapButton()
.br
.RS
.TP 3
Types:

Option = {pos, {X::integer(), Y::integer()}} | {size, {W::integer(), H::integer()}} | {style, integer()} | {validator, wx() (see module wx)}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
create(This::wxBitmapButton(), Parent::wxWindow() (see module wxWindow), Id::integer(), Bitmap::wxBitmap() (see module wxBitmap)) -> bool()
.br
.RS
.LP
Equivalent to \fBcreate(This, Parent, Id, Bitmap, [])\fR\&\&.
.RE
.LP
.B
create(This::wxBitmapButton(), Parent::wxWindow() (see module wxWindow), Id::integer(), Bitmap::wxBitmap() (see module wxBitmap), Options::[Option]) -> bool()
.br
.RS
.TP 3
Types:

Option = {pos, {X::integer(), Y::integer()}} | {size, {W::integer(), H::integer()}} | {style, integer()} | {validator, wx() (see module wx)}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getBitmapDisabled(This::wxBitmapButton()) -> wxBitmap() (see module wxBitmap)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getBitmapFocus(This::wxBitmapButton()) -> wxBitmap() (see module wxBitmap)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getBitmapLabel(This::wxBitmapButton()) -> wxBitmap() (see module wxBitmap)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getBitmapSelected(This::wxBitmapButton()) -> wxBitmap() (see module wxBitmap)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setBitmapDisabled(This::wxBitmapButton(), Disabled::wxBitmap() (see module wxBitmap)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setBitmapFocus(This::wxBitmapButton(), Focus::wxBitmap() (see module wxBitmap)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setBitmapLabel(This::wxBitmapButton(), Bitmap::wxBitmap() (see module wxBitmap)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setBitmapSelected(This::wxBitmapButton(), Sel::wxBitmap() (see module wxBitmap)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxBitmapButton()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>