.TH wxCalendarEvent 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxCalendarEvent \- See external documentation: wxCalendarEvent.
.SH DESCRIPTION
.LP
See external documentation: wxCalendarEvent\&.
.RS 2
.TP 2
.B
Use \fBwxEvtHandler:connect/3\fR\& with EventType::
\fIcalendar_sel_changed\fR\&, \fIcalendar_day_changed\fR\&, \fIcalendar_month_changed\fR\&, \fIcalendar_year_changed\fR\&, \fIcalendar_doubleclicked\fR\&, \fIcalendar_weekday_clicked\fR\&
.RE
.LP
See also the message variant \fB#wxCalendar{\fR\&} event record type\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxDateEvent\fR\& 
.br
\fBwxCommandEvent\fR\& 
.br
\fBwxEvent\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxCalendarEvent()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
getWeekDay(This::wxCalendarEvent()) -> WeekDay
.br
.RS
.TP 3
Types:

WeekDay = integer()
.br
.RE
.RS
.LP
See external documentation\&. 
.br
WeekDay is one of ?wxDateTime_Sun | ?wxDateTime_Mon | ?wxDateTime_Tue | ?wxDateTime_Wed | ?wxDateTime_Thu | ?wxDateTime_Fri | ?wxDateTime_Sat | ?wxDateTime_Inv_WeekDay
.RE
.SH AUTHORS
.LP

.I
<>