.TH wxChildFocusEvent 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxChildFocusEvent \- See external documentation: wxChildFocusEvent.
.SH DESCRIPTION
.LP
See external documentation: wxChildFocusEvent\&.
.RS 2
.TP 2
.B
Use \fBwxEvtHandler:connect/3\fR\& with EventType::
\fIchild_focus\fR\&
.RE
.LP
See also the message variant \fB#wxChildFocus{\fR\&} event record type\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxCommandEvent\fR\& 
.br
\fBwxEvent\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxChildFocusEvent()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
getWindow(This::wxChildFocusEvent()) -> wxWindow() (see module wxWindow)
.br
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>