.TH wxChoice 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxChoice \- See external documentation: wxChoice.
.SH DESCRIPTION
.LP
See external documentation: wxChoice\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxControlWithItems\fR\& 
.br
\fBwxControl\fR\& 
.br
\fBwxWindow\fR\& 
.br
\fBwxEvtHandler\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxChoice()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxChoice()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Parent::wxWindow() (see module wxWindow), Id::integer()) -> wxChoice()
.br
.RS
.LP
Equivalent to \fBnew(Parent, Id, [])\fR\&\&.
.RE
.LP
.B
new(Parent::wxWindow() (see module wxWindow), Id::integer(), Options::[Option]) -> wxChoice()
.br
.RS
.TP 3
Types:

Option = {pos, {X::integer(), Y::integer()}} | {size, {W::integer(), H::integer()}} | {choices, [[string()]]} | {style, integer()} | {validator, wx() (see module wx)}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
create(This::wxChoice(), Parent::wxWindow() (see module wxWindow), Id::integer(), Pos::{X::integer(), Y::integer()}, Size::{W::integer(), H::integer()}, Choices::[[string()]]) -> bool()
.br
.RS
.LP
Equivalent to \fBcreate(This, Parent, Id, Pos, Size, Choices, [])\fR\&\&.
.RE
.LP
.B
create(This::wxChoice(), Parent::wxWindow() (see module wxWindow), Id::integer(), Pos::{X::integer(), Y::integer()}, Size::{W::integer(), H::integer()}, Choices::[[string()]], Options::[Option]) -> bool()
.br
.RS
.TP 3
Types:

Option = {style, integer()} | {validator, wx() (see module wx)}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
delete(This::wxChoice(), N::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getColumns(This::wxChoice()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setColumns(This::wxChoice()) -> ok
.br
.RS
.LP
Equivalent to \fBsetColumns(This, [])\fR\&\&.
.RE
.LP
.B
setColumns(This::wxChoice(), Options::[Option]) -> ok
.br
.RS
.TP 3
Types:

Option = {n, integer()}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxChoice()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>