.TH wxColourData 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxColourData \- See external documentation: wxColourData.
.SH DESCRIPTION
.LP
See external documentation: wxColourData\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxColourData()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxColourData()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Data::wxColourData()) -> wxColourData()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getChooseFull(This::wxColourData()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getColour(This::wxColourData()) -> colour() (see module wx)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getCustomColour(This::wxColourData(), I::integer()) -> colour() (see module wx)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setChooseFull(This::wxColourData(), Flag::bool()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setColour(This::wxColourData(), Colour::colour() (see module wx)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setCustomColour(This::wxColourData(), I::integer(), Colour::colour() (see module wx)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxColourData()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>