.TH wxControl 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxControl \- See external documentation: wxControl.
.SH DESCRIPTION
.LP
See external documentation: wxControl\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxWindow\fR\& 
.br
\fBwxEvtHandler\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxControl()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
getLabel(This::wxControl()) -> string()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setLabel(This::wxControl(), Label::string()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>