.TH wxColourPickerCtrl 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxColourPickerCtrl \- See external documentation: wxColourPickerCtrl.
.SH DESCRIPTION
.LP
See external documentation: wxColourPickerCtrl\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxPickerBase\fR\& 
.br
\fBwxControl\fR\& 
.br
\fBwxWindow\fR\& 
.br
\fBwxEvtHandler\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxColourPickerCtrl()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxColourPickerCtrl()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Parent::wxWindow() (see module wxWindow), Id::integer()) -> wxColourPickerCtrl()
.br
.RS
.LP
Equivalent to \fBnew(Parent, Id, [])\fR\&\&.
.RE
.LP
.B
new(Parent::wxWindow() (see module wxWindow), Id::integer(), Options::[Option]) -> wxColourPickerCtrl()
.br
.RS
.TP 3
Types:

Option = {col, colour() (see module wx)} | {pos, {X::integer(), Y::integer()}} | {size, {W::integer(), H::integer()}} | {style, integer()} | {validator, wx() (see module wx)}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
create(This::wxColourPickerCtrl(), Parent::wxWindow() (see module wxWindow), Id::integer()) -> bool()
.br
.RS
.LP
Equivalent to \fBcreate(This, Parent, Id, [])\fR\&\&.
.RE
.LP
.B
create(This::wxColourPickerCtrl(), Parent::wxWindow() (see module wxWindow), Id::integer(), Options::[Option]) -> bool()
.br
.RS
.TP 3
Types:

Option = {col, colour() (see module wx)} | {pos, {X::integer(), Y::integer()}} | {size, {W::integer(), H::integer()}} | {style, integer()} | {validator, wx() (see module wx)}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getColour(This::wxColourPickerCtrl()) -> colour() (see module wx)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setColour(This::wxColourPickerCtrl(), X::string() | term()) -> bool() | ok
.br
.RS
.LP
See external documentation\&. 
.br
Alternatives:
.LP
\fI setColour(This::wxColourPickerCtrl(), Text::string()) -> bool() \fR\& 
.LP
\fI setColour(This::wxColourPickerCtrl(), Col::wx:colour()) -> ok \fR\& 
.RE
.LP
.B
destroy(This::wxColourPickerCtrl()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>