.TH wxContextMenuEvent 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxContextMenuEvent \- See external documentation: wxContextMenuEvent.
.SH DESCRIPTION
.LP
See external documentation: wxContextMenuEvent\&.
.RS 2
.TP 2
.B
Use \fBwxEvtHandler:connect/3\fR\& with EventType::
\fIcontext_menu\fR\&
.RE
.LP
See also the message variant \fB#wxContextMenu{\fR\&} event record type\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxCommandEvent\fR\& 
.br
\fBwxEvent\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxContextMenuEvent()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
getPosition(This::wxContextMenuEvent()) -> {X::integer(), Y::integer()}
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setPosition(This::wxContextMenuEvent(), Pos::{X::integer(), Y::integer()}) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>