.TH wxDialog 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxDialog \- See external documentation: wxDialog.
.SH DESCRIPTION
.LP
See external documentation: wxDialog\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxTopLevelWindow\fR\& 
.br
\fBwxWindow\fR\& 
.br
\fBwxEvtHandler\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxDialog()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxDialog()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Parent::wxWindow() (see module wxWindow), Id::integer(), Title::string()) -> wxDialog()
.br
.RS
.LP
Equivalent to \fBnew(Parent, Id, Title, [])\fR\&\&.
.RE
.LP
.B
new(Parent::wxWindow() (see module wxWindow), Id::integer(), Title::string(), Options::[Option]) -> wxDialog()
.br
.RS
.TP 3
Types:

Option = {pos, {X::integer(), Y::integer()}} | {size, {W::integer(), H::integer()}} | {style, integer()}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
create(This::wxDialog(), Parent::wxWindow() (see module wxWindow), Id::integer(), Title::string()) -> bool()
.br
.RS
.LP
Equivalent to \fBcreate(This, Parent, Id, Title, [])\fR\&\&.
.RE
.LP
.B
create(This::wxDialog(), Parent::wxWindow() (see module wxWindow), Id::integer(), Title::string(), Options::[Option]) -> bool()
.br
.RS
.TP 3
Types:

Option = {pos, {X::integer(), Y::integer()}} | {size, {W::integer(), H::integer()}} | {style, integer()}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
createButtonSizer(This::wxDialog(), Flags::integer()) -> wxSizer() (see module wxSizer)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
createStdDialogButtonSizer(This::wxDialog(), Flags::integer()) -> wxStdDialogButtonSizer() (see module wxStdDialogButtonSizer)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
endModal(This::wxDialog(), RetCode::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getAffirmativeId(This::wxDialog()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getReturnCode(This::wxDialog()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isModal(This::wxDialog()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setAffirmativeId(This::wxDialog(), AffirmativeId::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setReturnCode(This::wxDialog(), ReturnCode::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
show(This::wxDialog()) -> bool()
.br
.RS
.LP
Equivalent to \fBshow(This, [])\fR\&\&.
.RE
.LP
.B
show(This::wxDialog(), Options::[Option]) -> bool()
.br
.RS
.TP 3
Types:

Option = {show, bool()}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
showModal(This::wxDialog()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxDialog()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>