.TH wxEvent 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxEvent \- See external documentation: wxEvent.
.SH DESCRIPTION
.LP
See external documentation: wxEvent\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxEvent()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
getId(This::wxEvent()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getSkipped(This::wxEvent()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getTimestamp(This::wxEvent()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isCommandEvent(This::wxEvent()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
resumePropagation(This::wxEvent(), PropagationLevel::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
shouldPropagate(This::wxEvent()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
skip(This::wxEvent()) -> ok
.br
.RS
.LP
Equivalent to \fBskip(This, [])\fR\&\&.
.RE
.LP
.B
skip(This::wxEvent(), Options::[Option]) -> ok
.br
.RS
.TP 3
Types:

Option = {skip, bool()}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
stopPropagation(This::wxEvent()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>