.TH wxGridCellFloatEditor 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxGridCellFloatEditor \- See external documentation: wxGridCellFloatEditor.
.SH DESCRIPTION
.LP
See external documentation: wxGridCellFloatEditor\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxGridCellEditor\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxGridCellFloatEditor()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxGridCellFloatEditor()
.br
.RS
.LP
Equivalent to \fBnew([])\fR\&\&.
.RE
.LP
.B
new(Options::[Option]) -> wxGridCellFloatEditor()
.br
.RS
.TP 3
Types:

Option = {width, integer()} | {precision, integer()}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setParameters(This::wxGridCellFloatEditor(), Params::string()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxGridCellFloatEditor()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>