.TH wxGraphicsObject 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxGraphicsObject \- See external documentation: wxGraphicsObject.
.SH DESCRIPTION
.LP
See external documentation: wxGraphicsObject\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxGraphicsObject()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
getRenderer(This::wxGraphicsObject()) -> wxGraphicsRenderer() (see module wxGraphicsRenderer)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isNull(This::wxGraphicsObject()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>