.TH wxGridCellEditor 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxGridCellEditor \- See external documentation: wxGridCellEditor.
.SH DESCRIPTION
.LP
See external documentation: wxGridCellEditor\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxGridCellEditor()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
create(This::wxGridCellEditor(), Parent::wxWindow() (see module wxWindow), Id::integer(), EvtHandler::wxEvtHandler() (see module wxEvtHandler)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isCreated(This::wxGridCellEditor()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setSize(This::wxGridCellEditor(), Rect::{X::integer(), Y::integer(), W::integer(), H::integer()}) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
show(This::wxGridCellEditor(), Show::bool()) -> ok
.br
.RS
.LP
Equivalent to \fBshow(This, Show, [])\fR\&\&.
.RE
.LP
.B
show(This::wxGridCellEditor(), Show::bool(), Options::[Option]) -> ok
.br
.RS
.TP 3
Types:

Option = {attr, wxGridCellAttr() (see module wxGridCellAttr)}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
paintBackground(This::wxGridCellEditor(), RectCell::{X::integer(), Y::integer(), W::integer(), H::integer()}, Attr::wxGridCellAttr() (see module wxGridCellAttr)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
beginEdit(This::wxGridCellEditor(), Row::integer(), Col::integer(), Grid::wxGrid() (see module wxGrid)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
endEdit(This::wxGridCellEditor(), Row::integer(), Col::integer(), Grid::wxGrid() (see module wxGrid)) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
reset(This::wxGridCellEditor()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
startingKey(This::wxGridCellEditor(), Event::wxKeyEvent() (see module wxKeyEvent)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
startingClick(This::wxGridCellEditor()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
handleReturn(This::wxGridCellEditor(), Event::wxKeyEvent() (see module wxKeyEvent)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>