.TH wxGridCellTextEditor 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxGridCellTextEditor \- See external documentation: wxGridCellTextEditor.
.SH DESCRIPTION
.LP
See external documentation: wxGridCellTextEditor\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxGridCellEditor\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxGridCellTextEditor()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxGridCellTextEditor()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setParameters(This::wxGridCellTextEditor(), Params::string()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxGridCellTextEditor()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>