.TH wxListItem 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxListItem \- See external documentation: wxListItem.
.SH DESCRIPTION
.LP
See external documentation: wxListItem\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxListItem()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxListItem()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Item::wxListItem()) -> wxListItem()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
clear(This::wxListItem()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getAlign(This::wxListItem()) -> WxListColumnFormat
.br
.RS
.TP 3
Types:

WxListColumnFormat = integer()
.br
.RE
.RS
.LP
See external documentation\&. 
.br
WxListColumnFormat is one of ?wxLIST_FORMAT_LEFT | ?wxLIST_FORMAT_RIGHT | ?wxLIST_FORMAT_CENTRE | ?wxLIST_FORMAT_CENTER
.RE
.LP
.B
getBackgroundColour(This::wxListItem()) -> colour() (see module wx)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getColumn(This::wxListItem()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getFont(This::wxListItem()) -> wxFont() (see module wxFont)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getId(This::wxListItem()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getImage(This::wxListItem()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getMask(This::wxListItem()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getState(This::wxListItem()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getText(This::wxListItem()) -> string()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getTextColour(This::wxListItem()) -> colour() (see module wx)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getWidth(This::wxListItem()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setAlign(This::wxListItem(), Align::WxListColumnFormat) -> ok
.br
.RS
.TP 3
Types:

WxListColumnFormat = integer()
.br
.RE
.RS
.LP
See external documentation\&. 
.br
WxListColumnFormat is one of ?wxLIST_FORMAT_LEFT | ?wxLIST_FORMAT_RIGHT | ?wxLIST_FORMAT_CENTRE | ?wxLIST_FORMAT_CENTER
.RE
.LP
.B
setBackgroundColour(This::wxListItem(), ColBack::colour() (see module wx)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setColumn(This::wxListItem(), Col::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setFont(This::wxListItem(), Font::wxFont() (see module wxFont)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setId(This::wxListItem(), Id::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setImage(This::wxListItem(), Image::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setMask(This::wxListItem(), Mask::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setState(This::wxListItem(), State::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setStateMask(This::wxListItem(), StateMask::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setText(This::wxListItem(), Text::string()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setTextColour(This::wxListItem(), ColText::colour() (see module wx)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setWidth(This::wxListItem(), Width::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxListItem()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>