.TH wxListItemAttr 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxListItemAttr \- See external documentation: wxListItemAttr.
.SH DESCRIPTION
.LP
See external documentation: wxListItemAttr\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxListItemAttr()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxListItemAttr()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(ColText::colour() (see module wx), ColBack::colour() (see module wx), Font::wxFont() (see module wxFont)) -> wxListItemAttr()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getBackgroundColour(This::wxListItemAttr()) -> colour() (see module wx)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getFont(This::wxListItemAttr()) -> wxFont() (see module wxFont)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getTextColour(This::wxListItemAttr()) -> colour() (see module wx)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
hasBackgroundColour(This::wxListItemAttr()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
hasFont(This::wxListItemAttr()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
hasTextColour(This::wxListItemAttr()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setBackgroundColour(This::wxListItemAttr(), ColBack::colour() (see module wx)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setFont(This::wxListItemAttr(), Font::wxFont() (see module wxFont)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setTextColour(This::wxListItemAttr(), ColText::colour() (see module wx)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxListItemAttr()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>