.TH wxLogNull 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxLogNull \- See external documentation: wxLogNull.
.SH DESCRIPTION
.LP
See external documentation: wxLogNull\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxLogNull()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxLogNull()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxLogNull()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>