.TH wxMask 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxMask \- See external documentation: wxMask.
.SH DESCRIPTION
.LP
See external documentation: wxMask\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxMask()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxMask()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Bitmap::wxBitmap() (see module wxBitmap)) -> wxMask()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Bitmap::wxBitmap() (see module wxBitmap), X::integer() | term()) -> wxMask()
.br
.RS
.LP
See external documentation\&. 
.br
Alternatives:
.LP
\fI new(Bitmap::wxBitmap:wxBitmap(), PaletteIndex::integer()) -> wxMask() \fR\& 
.LP
\fI new(Bitmap::wxBitmap:wxBitmap(), Colour::wx:colour()) -> wxMask() \fR\& 
.RE
.LP
.B
create(This::wxMask(), Bitmap::wxBitmap() (see module wxBitmap)) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
create(This::wxMask(), Bitmap::wxBitmap() (see module wxBitmap), X::integer() | term()) -> bool()
.br
.RS
.LP
See external documentation\&. 
.br
Alternatives:
.LP
\fI create(This::wxMask(), Bitmap::wxBitmap:wxBitmap(), PaletteIndex::integer()) -> bool() \fR\& 
.LP
\fI create(This::wxMask(), Bitmap::wxBitmap:wxBitmap(), Colour::wx:colour()) -> bool() \fR\& 
.RE
.LP
.B
destroy(This::wxMask()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>