.TH wxMouseCaptureChangedEvent 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxMouseCaptureChangedEvent \- See external documentation: wxMouseCaptureChangedEvent.
.SH DESCRIPTION
.LP
See external documentation: wxMouseCaptureChangedEvent\&.
.RS 2
.TP 2
.B
Use \fBwxEvtHandler:connect/3\fR\& with EventType::
\fImouse_capture_changed\fR\&
.RE
.LP
See also the message variant \fB#wxMouseCaptureChanged{\fR\&} event record type\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxEvent\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxMouseCaptureChangedEvent()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
getCapturedWindow(This::wxMouseCaptureChangedEvent()) -> wxWindow() (see module wxWindow)
.br
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>