.TH wxNavigationKeyEvent 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxNavigationKeyEvent \- See external documentation: wxNavigationKeyEvent.
.SH DESCRIPTION
.LP
See external documentation: wxNavigationKeyEvent\&.
.RS 2
.TP 2
.B
Use \fBwxEvtHandler:connect/3\fR\& with EventType::
\fInavigation_key\fR\&
.RE
.LP
See also the message variant \fB#wxNavigationKey{\fR\&} event record type\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxEvent\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxNavigationKeyEvent()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
getDirection(This::wxNavigationKeyEvent()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setDirection(This::wxNavigationKeyEvent(), BForward::bool()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isWindowChange(This::wxNavigationKeyEvent()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setWindowChange(This::wxNavigationKeyEvent(), BIs::bool()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isFromTab(This::wxNavigationKeyEvent()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setFromTab(This::wxNavigationKeyEvent(), BIs::bool()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getCurrentFocus(This::wxNavigationKeyEvent()) -> wxWindow() (see module wxWindow)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setCurrentFocus(This::wxNavigationKeyEvent(), Win::wxWindow() (see module wxWindow)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>