.TH wxNotifyEvent 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxNotifyEvent \- See external documentation: wxNotifyEvent.
.SH DESCRIPTION
.LP
See external documentation: wxNotifyEvent\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxCommandEvent\fR\& 
.br
\fBwxEvent\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxNotifyEvent()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
allow(This::wxNotifyEvent()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isAllowed(This::wxNotifyEvent()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
veto(This::wxNotifyEvent()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>