.TH wxPageSetupDialog 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxPageSetupDialog \- See external documentation: wxPageSetupDialog.
.SH DESCRIPTION
.LP
See external documentation: wxPageSetupDialog\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxPageSetupDialog()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new(Parent::wxWindow() (see module wxWindow)) -> wxPageSetupDialog()
.br
.RS
.LP
Equivalent to \fBnew(Parent, [])\fR\&\&.
.RE
.LP
.B
new(Parent::wxWindow() (see module wxWindow), Options::[Option]) -> wxPageSetupDialog()
.br
.RS
.TP 3
Types:

Option = {data, wxPageSetupDialogData() (see module wxPageSetupDialogData)}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getPageSetupData(This::wxPageSetupDialog()) -> wxPageSetupDialogData() (see module wxPageSetupDialogData)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
showModal(This::wxPageSetupDialog()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxPageSetupDialog()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>