.TH wxPen 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxPen \- See external documentation: wxPen.
.SH DESCRIPTION
.LP
See external documentation: wxPen\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxPen()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxPen()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Colour::colour() (see module wx)) -> wxPen()
.br
.RS
.LP
Equivalent to \fBnew(Colour, [])\fR\&\&.
.RE
.LP
.B
new(Colour::colour() (see module wx), Options::[Option]) -> wxPen()
.br
.RS
.TP 3
Types:

Option = {width, integer()} | {style, integer()}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getCap(This::wxPen()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getColour(This::wxPen()) -> colour() (see module wx)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getJoin(This::wxPen()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getStyle(This::wxPen()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getWidth(This::wxPen()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isOk(This::wxPen()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setCap(This::wxPen(), CapStyle::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setColour(This::wxPen(), Colour::colour() (see module wx)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setColour(This::wxPen(), Red::integer(), Green::integer(), Blue::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setJoin(This::wxPen(), JoinStyle::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setStyle(This::wxPen(), Style::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setWidth(This::wxPen(), Width::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxPen()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>