.TH wxPrintDialogData 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxPrintDialogData \- See external documentation: wxPrintDialogData.
.SH DESCRIPTION
.LP
See external documentation: wxPrintDialogData\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxPrintDialogData()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxPrintDialogData()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(DialogData::wxPrintDialogData() | wxPrintData() (see module wxPrintData)) -> wxPrintDialogData()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
enableHelp(This::wxPrintDialogData(), Flag::bool()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
enablePageNumbers(This::wxPrintDialogData(), Flag::bool()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
enablePrintToFile(This::wxPrintDialogData(), Flag::bool()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
enableSelection(This::wxPrintDialogData(), Flag::bool()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getAllPages(This::wxPrintDialogData()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getCollate(This::wxPrintDialogData()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getFromPage(This::wxPrintDialogData()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getMaxPage(This::wxPrintDialogData()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getMinPage(This::wxPrintDialogData()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getNoCopies(This::wxPrintDialogData()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getPrintData(This::wxPrintDialogData()) -> wxPrintData() (see module wxPrintData)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getPrintToFile(This::wxPrintDialogData()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getSelection(This::wxPrintDialogData()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getToPage(This::wxPrintDialogData()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isOk(This::wxPrintDialogData()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setCollate(This::wxPrintDialogData(), Flag::bool()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setFromPage(This::wxPrintDialogData(), V::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setMaxPage(This::wxPrintDialogData(), V::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setMinPage(This::wxPrintDialogData(), V::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setNoCopies(This::wxPrintDialogData(), V::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setPrintData(This::wxPrintDialogData(), PrintData::wxPrintData() (see module wxPrintData)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setPrintToFile(This::wxPrintDialogData(), Flag::bool()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setSelection(This::wxPrintDialogData(), Flag::bool()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setToPage(This::wxPrintDialogData(), V::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxPrintDialogData()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>