.TH wxPrintPreview 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxPrintPreview \- See external documentation: wxPrintPreview.
.SH DESCRIPTION
.LP
See external documentation: wxPrintPreview\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxPrintPreview()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new(Printout::wxPrintout() (see module wxPrintout)) -> wxPrintPreview()
.br
.RS
.LP
Equivalent to \fBnew(Printout, [])\fR\&\&.
.RE
.LP
.B
new(Printout::wxPrintout() (see module wxPrintout), Options::[Option]) -> wxPrintPreview()
.br
.RS
.TP 3
Types:

Option = {printoutForPrinting, wxPrintout() (see module wxPrintout)} | {data, wxPrintDialogData() (see module wxPrintDialogData)}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Printout::wxPrintout() (see module wxPrintout), PrintoutForPrinting::wxPrintout() (see module wxPrintout), Data::wxPrintData() (see module wxPrintData)) -> wxPrintPreview()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getCanvas(This::wxPrintPreview()) -> wxPreviewCanvas() (see module wxPreviewCanvas)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getCurrentPage(This::wxPrintPreview()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getFrame(This::wxPrintPreview()) -> wxFrame() (see module wxFrame)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getMaxPage(This::wxPrintPreview()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getMinPage(This::wxPrintPreview()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getPrintout(This::wxPrintPreview()) -> wxPrintout() (see module wxPrintout)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getPrintoutForPrinting(This::wxPrintPreview()) -> wxPrintout() (see module wxPrintout)
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isOk(This::wxPrintPreview()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
paintPage(This::wxPrintPreview(), Canvas::wxPreviewCanvas() (see module wxPreviewCanvas), Dc::wxDC() (see module wxDC)) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
print(This::wxPrintPreview(), Interactive::bool()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
renderPage(This::wxPrintPreview(), PageNum::integer()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setCanvas(This::wxPrintPreview(), Canvas::wxPreviewCanvas() (see module wxPreviewCanvas)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setCurrentPage(This::wxPrintPreview(), PageNum::integer()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setFrame(This::wxPrintPreview(), Frame::wxFrame() (see module wxFrame)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setPrintout(This::wxPrintPreview(), Printout::wxPrintout() (see module wxPrintout)) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setZoom(This::wxPrintPreview(), Percent::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxPrintPreview()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>