.TH wxQueryNewPaletteEvent 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxQueryNewPaletteEvent \- See external documentation: wxQueryNewPaletteEvent.
.SH DESCRIPTION
.LP
See external documentation: wxQueryNewPaletteEvent\&.
.RS 2
.TP 2
.B
Use \fBwxEvtHandler:connect/3\fR\& with EventType::
\fIquery_new_palette\fR\&
.RE
.LP
See also the message variant \fB#wxQueryNewPalette{\fR\&} event record type\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxEvent\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxQueryNewPaletteEvent()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
setPaletteRealized(This::wxQueryNewPaletteEvent(), Realized::bool()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getPaletteRealized(This::wxQueryNewPaletteEvent()) -> bool()
.br
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>