.TH wxScrollEvent 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxScrollEvent \- See external documentation: wxScrollEvent.
.SH DESCRIPTION
.LP
See external documentation: wxScrollEvent\&.
.RS 2
.TP 2
.B
Use \fBwxEvtHandler:connect/3\fR\& with EventType::
\fIscroll_top\fR\&, \fIscroll_bottom\fR\&, \fIscroll_lineup\fR\&, \fIscroll_linedown\fR\&, \fIscroll_pageup\fR\&, \fIscroll_pagedown\fR\&, \fIscroll_thumbtrack\fR\&, \fIscroll_thumbrelease\fR\&, \fIscroll_changed\fR\&
.RE
.LP
See also the message variant \fB#wxScroll{\fR\&} event record type\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxCommandEvent\fR\& 
.br
\fBwxEvent\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxScrollEvent()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
getOrientation(This::wxScrollEvent()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getPosition(This::wxScrollEvent()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>