.TH wxSingleChoiceDialog 3 "wxErlang 0.99" "" "Erlang Module Definition"
.SH NAME
wxSingleChoiceDialog \- See external documentation: wxSingleChoiceDialog.
.SH DESCRIPTION
.LP
See external documentation: wxSingleChoiceDialog\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxDialog\fR\& 
.br
\fBwxTopLevelWindow\fR\& 
.br
\fBwxWindow\fR\& 
.br
\fBwxEvtHandler\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxSingleChoiceDialog()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxSingleChoiceDialog()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Parent::wxWindow() (see module wxWindow), Message::string(), Caption::string(), Choices::[[string()]]) -> wxSingleChoiceDialog()
.br
.RS
.LP
Equivalent to \fBnew(Parent, Message, Caption, Choices, [])\fR\&\&.
.RE
.LP
.B
new(Parent::wxWindow() (see module wxWindow), Message::string(), Caption::string(), Choices::[[string()]], Options::[Option]) -> wxSingleChoiceDialog()
.br
.RS
.TP 3
Types:

Option = {style, integer()} | {pos, {X::integer(), Y::integer()}}
.br
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getSelection(This::wxSingleChoiceDialog()) -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getStringSelection(This::wxSingleChoiceDialog()) -> string()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setSelection(This::wxSingleChoiceDialog(), Sel::integer()) -> ok
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxSingleChoiceDialog()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>