%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PullConsumer
%% Source: /builddir/build/BUILD/otp_src_R14B04/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PULLCONSUMER_HRL).
-define(COSEVENTCOMM_PULLCONSUMER_HRL, true).




-endif.


