%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_cosEventApp
%% Source: /builddir/build/BUILD/otp_src_R14B04/lib/cosEvent/src/cosEventApp.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTAPP_HRL).
-define(OE_COSEVENTAPP_HRL, true).




-endif.


