.TH ct_run 1 "common_test 1.5.5" "Ericsson AB" "User Commands"
.SH NAME
ct_run \- Program used for starting Common Test from the
    OS command line.
  
.SH DESCRIPTION
.LP
The \fIct_run\fR\& program is automatically installed with Erlang/OTP and Common Test (please see the Installation chapter in the Common Test User\&'s Guide for more information)\&. The program accepts a number of different start flags\&. Some flags trigger \fIct_run\fR\& to start the Common Test application and pass on data to it\&. Some flags start an Erlang node prepared for running Common Test in a particular mode\&.
.LP
There is an interface function that corresponds to this program, called \fIct:run_test/1\fR\&, for starting Common Test from the Erlang shell (or an Erlang program)\&. Please see the \fIct\fR\& man page for details\&.
.LP
\fIct_run\fR\& also accepts Erlang emulator flags\&. These are used when \fIct_run\fR\& calls \fIerl\fR\& to start the Erlang node (making it possible to e\&.g\&. add directories to the code server path, change the cookie on the node, start additional applications, etc)\&.
.LP
With the optional flag:
.LP
.nf
-erl_args
.fi
.LP
it\&'s possible to divide the options on the \fIct_run\fR\& command line into two groups, one that Common Test should process (those preceding \fI-erl_args\fR\&), and one it should completely ignore and pass on directly to the emulator (those following \fI-erl_args\fR\&)\&. Options preceding \fI-erl_args\fR\& that Common Test doesn\&'t recognize, also get passed on to the emulator untouched\&. By means of \fI-erl_args\fR\& the user may specify flags with the same name, but with different destinations, on the \fIct_run\fR\& command line\&.
.LP
If \fI-pa\fR\& or \fI-pz\fR\& flags are specified in the Common Test group of options (preceding \fI-erl_args\fR\&), relative directories will be converted to absolute and re-inserted into the code path by Common Test (to avoid problems loading user modules when Common Test changes working directory during test runs)\&. Common Test will however ignore \fI-pa\fR\& and \fI-pz\fR\& flags following \fI-erl_args\fR\& on the command line\&. These directories are added to the code path normally (i\&.e\&. on specified form)
.LP
If \fIct_run\fR\& is called with option:
.LP
.nf
-help
.fi
.LP
it prints all valid start flags to stdout\&.
.SH "RUN TESTS FROM COMMAND LINE"

.LP
.nf

	ct_run [-dir TestDir1 TestDir2 .. TestDirN] |
	[[-dir TestDir] -suite Suite1 Suite2 .. SuiteN
	 [[-group Group1 Group2 .. GroupN] [-case Case1 Case2 .. CaseN]]]
	[-step [config | keep_inactive]]
	[-config ConfigFile1 ConfigFile2 .. ConfigFileN]
	[-userconfig CallbackModule1 ConfigString1 and CallbackModule2
	 ConfigString2 and .. and CallbackModuleN ConfigStringN]
	[-decrypt_key Key] | [-decrypt_file KeyFile]
	[-label Label]
	[-logdir LogDir]
	[-logopts LogOpts]
	[-silent_connections [ConnType1 ConnType2 .. ConnTypeN]]
	[-stylesheet CSSFile]
	[-cover CoverCfgFile]
	[-event_handler EvHandler1 EvHandler2 .. EvHandlerN] |
        [-event_handler_init EvHandler1 InitArg1 and
	 EvHandler2 InitArg2 and .. EvHandlerN InitArgN]
	[-include InclDir1 InclDir2 .. InclDirN]
	[-no_auto_compile]
	[-muliply_timetraps Multiplier]
	[-scale_timetraps]
        [-repeat N [-force_stop]] |
        [-duration HHMMSS [-force_stop]] |
        [-until [YYMoMoDD]HHMMSS [-force_stop]]
	[-basic_html]
.fi
.SH "RUN TESTS USING TEST SPECIFICATION"

.LP
.nf

	ct_run -spec TestSpec1 TestSpec2 .. TestSpecN
	[-config ConfigFile1 ConfigFile2 .. ConfigFileN]
	[-userconfig CallbackModule1 ConfigString1 and CallbackModule2
         ConfigString2 and .. and CallbackModuleN ConfigStringN]
	[-decrypt_key Key] | [-decrypt_file KeyFile]
	[-label Label]
	[-logdir LogDir]
	[-logopts LogOpts]
	[-allow_user_terms]
	[-silent_connections [ConnType1 ConnType2 .. ConnTypeN]]
	[-stylesheet CSSFile]
	[-cover CoverCfgFile]
	[-event_handler EvHandler1 EvHandler2 .. EvHandlerN] |
        [-event_handler_init EvHandler1 InitArg1 and
	 EvHandler2 InitArg2 and .. EvHandlerN InitArgN]
	[-include InclDir1 InclDir2 .. InclDirN]
	[-no_auto_compile]
	[-muliply_timetraps Multiplier]
	[-scale_timetraps]
        [-repeat N [-force_stop]] |
        [-duration HHMMSS [-force_stop]] |
        [-until [YYMoMoDD]HHMMSS [-force_stop]]
	[-basic_html]
.fi
.SH "RUN TESTS IN WEB BASED GUI"

.LP
.nf

        ct_run -vts [-browser Browser]
        [-dir TestDir1 TestDir2 .. TestDirN] |
        [[dir TestDir] -suite Suite [[-group Group] [-case Case]]]
	[-config ConfigFile1 ConfigFile2 .. ConfigFileN]
	[-userconfig CallbackModule1 ConfigString1 and CallbackModule2
         ConfigString2 and .. and CallbackModuleN ConfigStringN]
	[-logopts LogOpts]
	[-decrypt_key Key] | [-decrypt_file KeyFile]
	[-include InclDir1 InclDir2 .. InclDirN]
	[-no_auto_compile]
	[-muliply_timetraps Multiplier]
	[-scale_timetraps]
	[-basic_html]
.fi
.SH "REFRESH THE HTML INDEX FILES"

.LP
.nf

	ct_run -refresh_logs [-logdir LogDir] [-basic_html]
.fi
.SH "RUN CT IN INTERACTIVE MODE"

.LP
.nf

	ct_run -shell
	[-config ConfigFile1 ConfigFile2 ... ConfigFileN]
	[-userconfig CallbackModule1 ConfigString1 and CallbackModule2
         ConfigString2 and .. and CallbackModuleN ConfigStringN]
	[-decrypt_key Key] | [-decrypt_file KeyFile]
.fi
.SH "START A COMMON TEST MASTER NODE"

.LP
.nf

	ct_run -ctmaster
.fi
.SH "SEE ALSO"

.LP
Please read the \fBRunning Test Suites\fR\& chapter in the Common Test User\&'s Guide for information about the meaning of the different start flags\&.