%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_Coordinator
%% Source: /builddir/build/BUILD/otp_src_R14B04/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_COORDINATOR_HRL).
-define(COSTRANSACTIONS_COORDINATOR_HRL, true).




-endif.


