%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: ETraP_Server
%% Source: /builddir/build/BUILD/otp_src_R14B04/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ETRAP_SERVER_HRL).
-define(ETRAP_SERVER_HRL, true).




-endif.


