%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosTransactions
%% Source: /builddir/build/BUILD/otp_src_R14B04/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSTRANSACTIONS_HRL).
-define(OE_COSTRANSACTIONS_HRL, true).




-endif.


