%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTimerEvent_TimerEventService
%% Source: /builddir/build/BUILD/otp_src_R14B04/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIMEREVENT_TIMEREVENTSERVICE_HRL).
-define(COSTIMEREVENT_TIMEREVENTSERVICE_HRL, true).




-endif.


