%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime_UTO
%% Source: /builddir/build/BUILD/otp_src_R14B04/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_UTO_HRL).
-define(COSTIME_UTO_HRL, true).




-endif.


