%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: TimeBase
%% Source: /builddir/build/BUILD/otp_src_R14B04/lib/cosTime/src/TimeBase.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(TIMEBASE_HRL).
-define(TIMEBASE_HRL, true).


-record('TimeBase_UtcT', {time, inacclo, inacchi, tdf}).
-record('TimeBase_IntervalT', {lower_bound, upper_bound}).


-endif.


