%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNaming
%% Source: /builddir/build/BUILD/otp_src_R14B04/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNAMING_HRL).
-define(COSNAMING_HRL, true).


-record('CosNaming_NameComponent', {id, kind}).
-record('CosNaming_Binding', {binding_name, binding_type}).


-endif.


