.TH observer 7 "observer 0.9.10" "Ericsson AB" "Erlang Application Definition"
.SH NAME
observer \- The Observer Application
.SH DESCRIPTION
.LP
This chapter describes the \fIOBSERVER\fR\& application in OTP, which provides tools for tracing and investigation of distributed systems\&.
.SH "CONFIGURATION"

.LP
There are currently no configuration parameters available for this application\&.
.SH "SEE ALSO"

.LP
