.TH STDLIB 7 "stdlib 1.17.5" "Ericsson AB" "Erlang Application Definition"
.SH NAME
STDLIB \- The STDLIB Application
.SH DESCRIPTION
.LP
The STDLIB is mandatory in the sense that the minimal system based on Erlang/OTP consists of Kernel and STDLIB\&. The STDLIB application contains no services\&.
.SH "CONFIGURATION"

.LP
The following configuration parameters are defined for the STDLIB application\&. See \fIapp(4)\fR\& for more information about configuration parameters\&.
.RS 2
.TP 2
.B
\fIshell_esc = icl | abort\fR\&:
This parameter can be used to alter the behaviour of the Erlang shell when ^G is pressed\&.
.TP 2
.B
\fIrestricted_shell = module()\fR\&:
This parameter can be used to run the Erlang shell in restricted mode\&.
.TP 2
.B
\fIshell_catch_exception = bool()\fR\&:
This parameter can be used to set the exception handling of the Erlang shell\&'s evaluator process\&.
.TP 2
.B
\fIshell_history_length = integer() >= 0\fR\&:
This parameter can be used to determine how many commands are saved by the Erlang shell\&.
.TP 2
.B
\fIshell_prompt_func = {Mod, Func} | default\fR\&:
where
.RS 2
.TP 2
*
\fIMod = atom()\fR\&
.LP
.TP 2
*
\fIFunc = atom()\fR\&
.LP
.RE

.RS 2
.LP
This parameter can be used to set a customized Erlang shell prompt function\&.
.RE
.TP 2
.B
\fIshell_saved_results = integer() >= 0\fR\&:
This parameter can be used to determine how many results are saved by the Erlang shell\&.
.RE
.SH "SEE ALSO"

.LP
\fBapp(4)\fR\&, \fBapplication(3)\fR\&, \fBshell(3)\fR\&,