%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotification_AdminPropertiesAdmin
%% Source: /builddir/build/BUILD/otp_src_R14B04/lib/cosNotification/src/CosNotification.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFICATION_ADMINPROPERTIESADMIN_HRL).
-define(COSNOTIFICATION_ADMINPROPERTIESADMIN_HRL, true).




-endif.


