%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventDomainAdmin
%% Source: /builddir/build/BUILD/otp_src_R14B04/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTDOMAINADMIN_HRL).
-define(OE_COSEVENTDOMAINADMIN_HRL, true).




-endif.


